### ISSUE TITLE
Select Menu users

### ISSUE THREAD

**Issue by D3ord3NidAm** [nizeic/Dodong#11]
How can I make it so that only the person who sends the (together) command can use the select menu?

**Comment by nizeic** [comment]
Sorry for the late response.

We have no plans to implement this, but you can probably store the author/member object of the command somewhere and check if the author matches with the sender of the selectmenu interaction.

https://discord.js.org/#/docs/discord.js/stable/class/Message?scrollTo=member
https://discord.js.org/#/docs/discord.js/stable/class/Interaction?scrollTo=member
