### ISSUE TITLE
Hi I fixed the other issue but now I ran to another problem. 

### ISSUE THREAD

**Issue by UnknownUW** [nizeic/Dodong#18]
The problem with this issue is whenever I play any sort of music. It will show me this error. Can you help me fix this issue thank you. 

Error: Error: Cannot find module '/home/runner/ZeFZmAtaX8I/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.24/opus.node'
Require stack:
- /home/runner/ZeFZmAtaX8I/node_modules/@discordjs/opus/lib/index.js
- /home/runner/ZeFZmAtaX8I/node_modules/prism-media/src/util/loader.js
- /home/runner/ZeFZmAtaX8I/node_modules/prism-media/src/opus/Opus.js
- /home/runner/ZeFZmAtaX8I/node_modules/prism-media/src/opus/index.js
- /home/runner/ZeFZmAtaX8I/node_modules/prism-media/src/index.js
- /home/runner/ZeFZmAtaX8I/node_modules/discord-player/dist/smoothVolume.js
- /home/runner/ZeFZmAtaX8I/node_modules/discord-player/dist/index.js
- /home/runner/ZeFZmAtaX8I/structures/client.js
- /home/runner/ZeFZmAtaX8I/index.js
Error: Cannot find module 'node-opus'
Require stack:
- /home/runner/ZeFZmAtaX8I/node_modules/prism-media/src/util/loader.js
- /home/runner/ZeFZmAtaX8I/node_modules/prism-media/src/opus/Opus.js
- /home/runner/ZeFZmAtaX8I/node_modules/prism-media/src/opus/index.js
- /home/runner/ZeFZmAtaX8I/node_modules/prism-media/src/index.js
- /home/runner/ZeFZmAtaX8I/node_modules/discord-player/dist/smoothVolume.js
- /home/runner/ZeFZmAtaX8I/node_modules/discord-player/dist/index.js
- /home/runner/ZeFZmAtaX8I/structures/client.js
- /home/runner/ZeFZmAtaX8I/index.js
Error: Cannot find module 'opusscript'
Require stack:
- /home/runner/ZeFZmAtaX8I/node_modules/prism-media/src/util/loader.js
- /home/runner/ZeFZmAtaX8I/node_modules/prism-media/src/opus/Opus.js
- /home/runner/ZeFZmAtaX8I/node_modules/prism-media/src/opus/index.js
- /home/runner/ZeFZmAtaX8I/node_modules/prism-media/src/index.js
- /home/runner/ZeFZmAtaX8I/node_modules/discord-player/dist/smoothVolume.js
- /home/runner/ZeFZmAtaX8I/node_modules/discord-player/dist/index.js
- /home/runner/ZeFZmAtaX8I/structures/client.js
- /home/runner/ZeFZmAtaX8I/index.js
    at Object.loader [as require] (/home/runner/ZeFZmAtaX8I/node_modules/prism-media/src/util/loader.js:12:9)
    at loadOpus (/home/runner/ZeFZmAtaX8I/node_modules/prism-media/src/opus/Opus.js:17:17)
    at new OpusStream (/home/runner/ZeFZmAtaX8I/node_modules/prism-media/src/opus/Opus.js:46:10)
    at new Encoder (/home/runner/ZeFZmAtaX8I/node_modules/prism-media/src/opus/Opus.js:149:5)
    at Object.transformer (/home/runner/ZeFZmAtaX8I/node_modules/@discordjs/voice/dist/index.js:8:13311)
    at /home/runner/ZeFZmAtaX8I/node_modules/@discordjs/voice/dist/index.js:8:16735
    at Array.map (<anonymous>)
    at We (/home/runner/ZeFZmAtaX8I/node_modules/@discordjs/voice/dist/index.js:8:16726)
    at StreamDispatcher.createStream (/home/runner/ZeFZmAtaX8I/node_modules/discord-player/dist/VoiceInterface/StreamDispatcher.js:116:62)
    at Queue.<anonymous> (/home/runner/ZeFZmAtaX8I/node_modules/discord-player/dist/Structures/Queue.js:699:46)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dodong@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dodong@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-03-23T23_06_19_065Z-debug.log
exit status 1

**Comment by nizeic** [comment]
what version of nodejs are you using?
```sh
node -v
```
if it's below v16, run this script from replit's **Shell**, not the Console
```sh
npm init -y && npm i --save-dev node@16 && npm config set prefix=$(pwd)/node_modules/node && export PATH=$(pwd)/node_modules/node/bin:$PATH
```

if it still doesnt work, try reinstalling @discordjs/opus
```sh
npm uninstall @discordjs/opus && npm install @discordjs/opus -verbose
```
