### ISSUE TITLE
Docker Instructions missing one space

### ISSUE THREAD

**Issue by DudeShift** [nizeic/Dodong#26]
For the "Run the Docker image" step the code / command listed is "`docker run -d -it --name dodong--restart unless-stopped dodong`" however there is a missing space that is needed between dodong and --restart. 

The code / command should be:

`docker run -d -it --name dodong --restart unless-stopped dodong`

**Comment by nizeic** [comment]
fixed in https://github.com/nizeic/Dodong/commit/7b06232e118c72fa3471966019993d22bca08d43. thanks
