### ISSUE TITLE
LavaLink

### ISSUE THREAD

**Issue by SpaceLeft** [nizeic/Dodong#8]
you can update it lavalink i hope you do it.

**Comment by nizeic** [comment]
discord-player with the discordjs/voice module is working fine for now so no, we have no plans to switch to Lavalink.

you can use other bots (like [this one](https://github.com/SudhanPlayz/Discord-MusicBot) and [this one](https://github.com/Tomato6966/discord-js-lavalink-Music-Bot-erela-js)) that use Lavalink alongside discord.js, or you can also fork this project with your own modifications if you want :)
